import uuid
from django.db import models



class Story(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255, default="New Story")
    generated_story = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Stories"

class Image(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    image = models.ImageField(upload_to='images/')
    story = models.ForeignKey(Story, related_name='stories',
                                on_delete=models.CASCADE, null=True, blank=True)

    caption = models.TextField()  # Stores the caption generated by Azure Vision API for the image
    caption_confidence = models.FloatField()

    def __str__(self):
        return self.caption


