# Generated by Django 4.2.7 on 2024-08-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azureai', '0002_alter_story_options_alter_image_id_alter_story_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='New Story', max_length=255),
        ),
    ]
